spring.application.name=api-project
#cấu hình server
server.port=8086

#cấu hình postgre
spring.datasource.url=jdbc:postgresql://localhost:5432/db_api_project
spring.datasource.username=postgres
spring.datasource.password=tri1412
# spring.datasource.driver-class-name=org.postgresql.Driver

#Cấu hình Hibernate/JPA
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

#JWT
jwt.secret = ShC32QVTo2SneU86cRDBhzJUd0Cm+6bXORXMjqOROdAmi0a4ZrELq0Ns0rAXI8vuyVRj62IXO8TH4pL/UL7i1w==
# 15 mins
jwt.accessToken.expiration=90000
# 15 days
jwt.refreshToken.expiration=15